INSERT INTO SHOWS (SHOW_ID, MOVIE_NAME, THEATRE_NAME, CITY, START_TIME, PRICE)
VALUES (1, 'Avengers', 'PVR Koramangala', 'Bangalore', '2026-04-10T10:00:00', 200);

INSERT INTO SHOWS (SHOW_ID, MOVIE_NAME, THEATRE_NAME, CITY, START_TIME, PRICE)
VALUES (2, 'Avengers', 'PVR Koramangala', 'Bangalore', '2026-04-10T14:00:00', 200);

INSERT INTO SHOWS (SHOW_ID, MOVIE_NAME, THEATRE_NAME, CITY, START_TIME, PRICE)
VALUES (3, 'Avengers', 'INOX Forum', 'Bangalore', '2026-04-10T18:00:00', 220);

INSERT INTO SHOWS (SHOW_ID, MOVIE_NAME, THEATRE_NAME, CITY, START_TIME, PRICE)
VALUES (4, 'Batman', 'INOX Forum', 'Bangalore', '2026-04-11T15:00:00', 180);

INSERT INTO SHOWS (SHOW_ID, MOVIE_NAME, THEATRE_NAME, CITY, START_TIME, PRICE)
VALUES (5, 'Batman', 'INOX Forum', 'Bangalore', '2026-04-11T15:00:00', 180);

INSERT INTO SHOWS (SHOW_ID, MOVIE_NAME, THEATRE_NAME, CITY, START_TIME, PRICE)
VALUES (6, 'Batman', 'INOX Forum', 'Bangalore', '2026-04-11T15:00:00', 180);

INSERT INTO SHOWS (SHOW_ID, MOVIE_NAME, THEATRE_NAME, CITY, START_TIME, PRICE)
VALUES (7, 'Batman', 'INOX Forum', 'Bangalore', '2026-04-12T15:00:00', 180);

INSERT INTO SHOWS (SHOW_ID, MOVIE_NAME, THEATRE_NAME, CITY, START_TIME, PRICE)
VALUES (8, 'Batman', 'INOX Forum', 'Bangalore', '2026-04-10T15:00:00', 180);

INSERT INTO SHOWS (SHOW_ID, MOVIE_NAME, THEATRE_NAME, CITY, START_TIME, PRICE)
VALUES (9, 'Batman', 'INOX Forum', 'Bangalore', '2026-04-10T15:00:00', 180);


INSERT INTO TICKET (TICKED_ID, SHOW_ID, SEAT_NUMBER, BOOKING_STATUS)
VALUES (1, 1, 'A1', 'AVAILABLE');

INSERT INTO TICKET (TICKED_ID, SHOW_ID, SEAT_NUMBER, BOOKING_STATUS)
VALUES (2, 1, 'A2', 'AVAILABLE');

INSERT INTO TICKET (TICKED_ID, SHOW_ID, SEAT_NUMBER, BOOKING_STATUS)
VALUES (3, 2, 'A1', 'AVAILABLE');

INSERT INTO TICKET (TICKED_ID, SHOW_ID, SEAT_NUMBER, BOOKING_STATUS)
VALUES (4, 2, 'A2', 'AVAILABLE');